Repository CMU-Perceptual-Computing-Lab/openpose, pull requests merged in 2018-06, with the labels that each got.

#624 bug fix to nmsBaseCL. OpenCL min version set to 120
  .gitignore
  3rdparty/osx/install_deps.sh
  CMakeLists.txt
  cmake/Cuda.cmake
  cmake/Modules/FindCuDNN.cmake
  cmake/Modules/FindGlog.cmake
  doc/installation.md
  examples/CMakeLists.txt
  examples/calibration/CMakeLists.txt
  examples/openpose/CMakeLists.txt
  examples/tests/CMakeLists.txt
  examples/tutorial_add_module/CMakeLists.txt
  examples/tutorial_pose/CMakeLists.txt
  examples/tutorial_thread/CMakeLists.txt
  examples/tutorial_wrapper/CMakeLists.txt
  include/openpose/gpu/opencl.hcl
  src/openpose/3d/CMakeLists.txt
  src/openpose/CMakeLists.txt
  src/openpose/calibration/CMakeLists.txt
  src/openpose/calibration/cameraParameterEstimation.cpp
  src/openpose/core/CMakeLists.txt
  src/openpose/face/CMakeLists.txt
  src/openpose/filestream/CMakeLists.txt
  src/openpose/gpu/CMakeLists.txt
  src/openpose/gpu/opencl.cpp
  src/openpose/gui/CMakeLists.txt
  src/openpose/hand/CMakeLists.txt
  src/openpose/net/CMakeLists.txt
  src/openpose/net/nmsBaseCL.cpp
  src/openpose/net/resizeAndMergeBaseCL.cpp
  src/openpose/pose/CMakeLists.txt
  src/openpose/pose/poseRenderer.cpp
  src/openpose/producer/CMakeLists.txt
  src/openpose/thread/CMakeLists.txt
  src/openpose/tracking/CMakeLists.txt
  src/openpose/utilities/CMakeLists.txt
  src/openpose/utilities/fileSystem.cpp
  src/openpose/wrapper/CMakeLists.txt
Labels: bug/typo, enhancement, fixed/added in newer versions

#648 Amd fix and Python API
  CMakeLists.txt
  doc/installation.md
  doc/python_module.md
  examples/CMakeLists.txt
  examples/tests/clTest.cpp
  examples/tutorial_python/1_extract_pose.py
  examples/tutorial_python/2_pose_from_heatmaps.py
  examples/tutorial_python/CMakeLists.txt
  include/openpose/gpu/opencl.hcl
  include/openpose/net/resizeAndMergeBase.hpp
  include/openpose/net/resizeAndMergeCaffe.hpp
  include/openpose/pose/poseParameters.hpp
  python/CMakeLists.txt
  python/openpose/CMakeLists.txt
  python/openpose/__init__.py
  python/openpose/_openpose.cpp
  python/openpose/openpose.py
  src/openpose/gpu/opencl.cpp
  src/openpose/net/nmsBaseCL.cpp
  src/openpose/net/resizeAndMergeBaseCL.cpp
  src/openpose/net/resizeAndMergeCaffe.cpp
Labels: enhancement

#670 fix global includes of tracking module
  include/openpose/headers.hpp
Labels: bug/typo, fixed/added in newer versions

#690 Update openpose.py - Wrong lib/bin path name
  python/openpose/openpose.py
Labels: bug/typo, fixed/added in newer versions

#691 Allow Windows run on Debug Build for Python
  python/openpose/openpose.py
Labels: bug/typo, fixed/added in newer versions
