Repository CMU-Perceptual-Computing-Lab/openpose, pull requests merged in 2019-01, with the labels that each got.

#989 Add files for install openpose under Jetpack 3.3
  doc/installation_jetson_tx2_jetpack3.3.md
  ubuntu/Makefile.config.Ubuntu16_cuda9_JetsonTX2_caffe
  ubuntu/Makefile.config.Ubuntu16_cuda9_JetsonTX2_openpose
  ubuntu/install_caffe_JetsonTX2_JetPack3.3.sh
  ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh
  ubuntu/install_openpose_JetsonTX2_JetPack3.3.sh
Labels: enhancement, fixed/added in newer versions

#1007 expression change to support opencl on nvidia
  src/openpose/net/bodyPartConnectorBaseCL.cpp
Labels: bug/typo, fixed/added in newer versions

#975 Unity plugin
  CMakeLists.txt
  include/openpose/headers.hpp
  include/openpose/unity/headers.hpp
  include/openpose/unity/unityBinding.hpp
  src/openpose/gui/CMakeLists.txt
  src/openpose/pose/CMakeLists.txt
  src/openpose/unity/CMakeLists.txt
  src/openpose/unity/unityBinding.cpp
  src/openpose/utilities/errorAndLog.cpp
Labels: enhancement

#1021 Added Travis build for Mac
  .travis.yml
  scripts/osx/install_deps.sh
  scripts/travis/configure_cmake.sh
  scripts/travis/install_deps_osx.sh
  scripts/travis/run_make.sh
Labels: enhancement

#1049 Update README.md
  README.md
Labels: bug/typo, fixed/added in newer versions
