Repository CMU-Perceptual-Computing-Lab/openpose, pull requests merged in 2019-02, with the labels that each got.

#1066 Unity binding cpp - updated parameters
  src/openpose/unity/unityBinding.cpp
Labels: UnityPlugin

#1077 target link mac
  src/openpose/unity/CMakeLists.txt
Labels: bug/typo, fixed/added in newer versions

#1080 add config debug, remove set multithread
  src/openpose/unity/unityBinding.cpp
Labels: enhancement, fixed/added in newer versions

#1083 Mac fix opencl
  CMakeLists.txt
  doc/installation.md
  scripts/osx/mac_opencl_patch.txt
  src/openpose/core/arrayCpuGpu.cpp
Labels: enhancement, fixed/added in newer versions

#1086 updated opencl travis scripts
  .travis.yml
  scripts/travis/configure_cmake.sh
  scripts/travis/defaults.sh
  scripts/ubuntu/install_deps.sh
Labels: enhancement, fixed/added in newer versions

#1096 Clean up Unity error logging message
  src/openpose/unity/unityBinding.cpp
  src/openpose/utilities/errorAndLog.cpp
Labels: enhancement, fixed/added in newer versions
